---
version: "3.4"
services:
  serv2:
    image: nginx
    ports:
      - "80:80"
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "0.5"
          memory: 512M 
    healthcheck:
      test: stat /usr/share/nginx/html/index.html
      interval: 10s
      timeout: 10s
      retries: 3
      start_period: 10s 

